<div class="container-fluid">



<?php if (count($this->messages) > 0): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php foreach ($this->messages as $message): ?>
                <span><?php echo current($message); ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>


    <h1 class="page-header">Registro de Productos</h1>
    <div style="position: absolute; z-index: 9999; <?php echo ($this->auth->getIdentity()->role === 'administrador') ? 'display:block;' : 'display:none;'; ?>">
    </div>
    <div class="row">



<!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->

<form id="form_productos" name="form_productos" enctype="multipart/form-data" action="<?php echo $this->baseUrl('/productos/add') ?>" method="post"><div>

    <input type="hidden" id="id" name="id"  value="<?php echo time();?>">

<div class="form-group">

<label for="estado" class="required">Categoria  *</label>

<select name="categoria" id="categoria" class="form-control">
    
            <option value="">--Categoria--</option>
                    <?php foreach ($this->categorias as $categoria): ?>
                    <option value="<?php echo $categoria->id; ?>" ><?php echo utf8_encode($categoria->titulo); ?></option>
                    <?php endforeach; ?>


</select>

</div>


<label for="nombre" class="required">Codigo *</label>
<input type="text" name="codigo" id="codigo" value="<?php echo time();?>" class="form-control" placeholder="Codigo">
</div>
<div class="form-group">
<label for="nombre" class="required">Nombre *</label>
<input type="text" name="nombre" id="nombre" value="" class="form-control" placeholder="Nombre">
</div>


<div class="form-group">
<label for="email" class="optional">Descripcion Corta</label>

<textarea  name="descripcion_corta" id="descripcion_corta" value="" class="form-control" placeholder="Descripcion Corta" ></textarea>

</div>




<div class="form-group">
<label for="email" class="optional">Descripcion</label>

<textarea  name="descripcion" id="descripcion" value="" class="form-control" placeholder="Descripcion" ></textarea>

</div>

<div class="form-group">
<label for="fecha_nac" class="required">Unidad *</label>

<input type="text" name="unidad" id="unidad" value="" class="form-control " placeholder="Saco de 1kg">
</div>

<div class="form-group">
<label for="fecha_nac" class="required">Costo *</label>

<input type="text" name="costo" id="costo" value="" class="form-control " placeholder="840,00">
</div>




<div class="form-group">
<label for="fecha_nac" class="required">Precio *</label>

<input type="text" name="precio" id="precio" value="" class="form-control " placeholder="840,00">
</div>


<div class="form-group">
<label for="fecha_nac" class="required">Oferta *</label>

<input type="text" name="oferta" id="oferta" value="" class="form-control " placeholder="840,00">
</div>

 <div class="col-sm-12">
      
         <div class="carga">
         <div class="row"></div> </div>
    <div class="loader">  </div>

    <div id="fileuploader"> Cargar Imagenes
    </div>

    </div>

<dt id="buttons-label">&#160;</dt><dd id="buttons-element"><fieldset id="fieldset-buttons"><dl>

<input type="submit" name="btn_submit" id="btn_submit" value="Guardar" class="btn btn-default">

<a name="btn_cancel" href="wake/productos" id="btn_cancel" type="button" class="btn btn-danger">Cancelar</a></dl></fieldset></dd></div></form> 



<!--+++<?php// echo $this->EstForm; ?> ++++++++++++++++++++ Fin  del formulario+++++++++++++++ ++++++++++++-->



	<div class="alert alert-danger" role="alert">
		* Campos Requeridos 
	</div>




    </div>
    
</div>
