

     <!--banner-->
        <div class="" style="padding-bottom: 2em;color: #909090;padding-top: 1em; text-align: center;">
            <div class="container">
                <h3>
                  <a style="color: #909090; font-size: 0.75em;" href="<?php echo $this->baseUrl('/'); ?>">Inicio</a> / 
                  <a style="color: #ff0398; font-size: 0.75em;" href="#"><?php echo $this->categoria['titulo']; ?></a> </h3>
            </div>
        </div>
    <!--banner-->


        <!--content-->
            <div class="content">
                <div class="products-agileinfo">
                        <h2 class="tittle"><?php echo $this->categoria['titulo']; ?></h2>
                    <div class="container">
                        <div class="product-agileinfo-grids w3l">
                            <div class="col-md-3 product-agileinfo-grid">
                                <div class="categories">
                                    <h3>Categorias</h3>
                                    <ul class="tree-list-pad">
                                        <?php foreach ($this->categorias_menu as $cat_menu): ?>
                <li><a href="<?php echo $this->baseUrl('/productos/categoria/id/'.$cat_menu->id); ?>"><?php echo $cat_menu->titulo; ?></a></li>
                            <?php endforeach ?>
                                      
                                    </ul>
                                </div>
                                
                                <div class="top-rates">
                                    <h3>Mas Vendidos</h3>


                                    <?php   $ObjFotos = new Application_Model_DbTable_Fotos(); ?>


                                     <?php foreach ($this->aleatorios as $aleatorio): ?>

                                <?php $fotos=$ObjFotos->fetchAll('id_solicitud="'.$aleatorio->id.'"'); ?>

                                 <div class="recent-grids">
                                        <div class="recent-left">


                                            <?php $i=1; ?>
                                        <?php foreach ($fotos as $foto): ?>
                                            <?php if ($i==1): ?>
                                              
                                               

                                               <a href="<?php echo $this->baseUrl('productos/ver/id/'.$aleatorio->id); ?>"><img class="img-responsive " src="<?php echo $this->baseUrl('assets/images/'.$foto->foto); ?>" alt=""></a> 

                                              <?php $i++; ?>
                                            <?php endif ?>
                                            
                                        <?php endforeach ?>

                                        </div>
                                        <div class="recent-right">
                                            <h6 class="best2"><a href="<?php echo $this->baseUrl('productos/ver/id/'.$aleatorio->id); ?>"><?php echo $aleatorio->nombre; ?> </a></h6>
                                            <!--<p><del>$100.00</del> <em class="item_price">$09.00</em></p>-->


                                        </div>  
                                        <div class="clearfix"> </div>
                                    </div>

                                
                            <?php endforeach ?>


                        
                                </div>
                                
                                <div class="cat-img">
                                    <img class="img-responsive " src="images/45.jpg" alt="">
                                </div>
                            </div>
                            <div class="col-md-9 product-agileinfon-grid1 w3l">
                                
                               
                                <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">
                                    <ul id="myTab" class="nav1 nav1-tabs left-tab" role="tablist">
                                        
                                    <div id="myTabContent" class="tab-content">
                                        <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
                                            <div class="product-tab">



                                                <?php   $ObjFotos = new Application_Model_DbTable_Fotos(); ?>

                        <?php foreach ($this->relacionados as $rela): ?>

                                <?php $fotos=$ObjFotos->fetchRow('id_solicitud="'.$rela->id.'"'); ?>


                                                <div class="col-md-4 product-tab-grid simpleCart_shelfItem">
                                                    <div class="grid-arr" style="height: 33em; border-radius: 1em;">
                                                        <div  class="grid-arrival">
                                                            <figure>        
                                                                <a href="#" class="new-gri" data-toggle="modal" data-target="#myModal1">
                                                                    
                                                                
                                                                    <div class="grid-img">
                                                                        <img style="height: 250px"  src="<?php echo $this->baseUrl('assets/images/'.$fotos['foto']); ?>" class="img-responsive" alt="">
                                                                    </div>
                                                                
                                                                    

                                                                </a>        
                                                            </figure>   
                                                        </div>
                                                        
                                                         <div class="women" style="padding-left: 1em; padding-right: 1em;">
                                        <span class="size" style="font-size: 0.7em;text-align: left;"><?php echo $rela->unidad; ?> </span>
                                        <h6 style="height: 1.5em; text-align: left;"><a href="<?php echo $this->baseUrl('productos/ver/id/'.$rela->id); ?>"><?php echo $rela->nombre; ?></a></h6>
                                        

                                        <p style="text-align: left;"><em class="item_price">$<?php echo intval($rela->oferta) ?></em></p>
                                        
                                        <a style="color: #fff;background-color: #ff0398;border-color: #ff0398; width: 100%; border-radius: 1em;" href="<?php echo $this->baseUrl('productos/ver/id/'.$rela->id); ?>" data-text="Agregar Al Carrito" class="btn btn-primary">Comprar</a>
                                    </div>
                                                    </div>
                                                </div>
                                                    <?php endforeach ?>

                               
                                             <div class="clearfix"></div>
                                            </div>
                                           
                                    </div>
                                </div>
                            </div>
                            <div class="clearfix"> </div>

                            <div class="row">
                                <div class="col-sm-12">
                                    <?php echo $this->categoria['descripcion']; ?>
                                </div>
                            </div>
                        </div>


                    </div>
                </div>
            </div>
        <!--content-->



