<section class="page-crumb">
    <!-- Page Content -->
    <div class="container">
        <!-- Page Heading/Breadcrumbs -->
        <div class="row">
            <div class="col-lg-12">
                <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Portfolio</li>
                </ol>
            </div>
        </div>
        <!-- /.row -->
    </div>
</section>  

<section class="portfolio-w3ls">    
    <div class="container">
        <h3 class="text-center w3layouts w3 w3l w3ls agileits agileinfo wthree w3-agileits agileits-w3layouts agile w3-agile">Nuestro Portafolio</h3>
        <p class="text-center w3layouts w3 w3l w3ls agileits agileinfo wthree w3-agileits agileits-w3layouts agile w3-agile">Nuestra estrategia de negocios busca satisfacer las necesidades financieras de los clientes, les presentamos nuestro portafolio de trabajos realizados, lo cuales fundamentan nuestra experiencia en avaluos y tasaciones...</p> 
        <div>
            <?php foreach ($this->portafolios as $porta): ?>
                <?php $imagen=$porta['imagen']; ?>
                <a class="example-image-link" href="<?php echo $this->baseUrl('/').$imagen; ?>" data-lightbox="example-set" data-title="<?php echo $porta['titulo'];  ?>">
                <img class="example-image img-responsive" src="<?php echo $this->baseUrl('/').$imagen; ?>" alt="<?php echo $porta['titulo'];  ?>" title="<?php echo $porta['titulo'];  ?>" />
            </a>  

            <?php endforeach ?>
            
            
        </div>      
    </div>  
</section>   