<script>
// Can also be used with $(document).ready()
$(window).load(function() {
  $('.flexslider').flexslider({
    animation: "slide",
    controlNav: "thumbnails"
  });
});
</script>
        <!--banner-->
        
    <!--banner-->
        <!--content-->
<!--content-->
        <div class="content">
            <!--single-->
            <div class="single-wl3">
                <div class="container">
                    <div class="single-grids">
                        <div class="col-md-12 single-grid">
                            <div clas="single-top">
                                <div class="single-left">
                                    <div class="flexslider">
                                        <ul class="slides">
                                            
                        <?php foreach ($this->fotos as $foto): ?>
                                <li data-thumb="<?php   echo $this->baseUrl('/assets/images/'.$foto->foto) ?>">
                                    <div class="thumb-image"> <img src="<?php   echo $this->baseUrl('/assets/images/'.$foto->foto) ?>" data-imagezoom="true" class="img-responsive"> </div>
                                </li>
                        <?php endforeach ?>

                                            
                                         </ul>
                                    </div>
                                </div>
                            <div class="single-right simpleCart_shelfItem">
                                <h4><?php   echo $this->detalles['nombre']; ?></h4>
                                
                               <!--<p class="price item_price"><?php   echo $this->detalles['precio']; ?></p>-->
                                <div class="description">
                                    <p><span>Descripcion : </span> <?php   echo $this->detalles['descripcion']; ?>.</p>
                                </div>
                                
                                <div class="women">
                                    <span class="size"><?php   echo $this->detalles['unidad']; ?></span>

                                    <p ><em class="item_price"><?php echo $this->detalles['oferta'] ?></em></p>


                                    <a target="_blank" href="https://wa.me/573224516244?text=Hola, quisiera mas información sobre el <?php echo $this->detalles['nombre']; ?> que vi en la pagina tiendacocomary.com" data-text="Add To Cart" class="my-cart-b item_add">Comprar</a>
                                </div>
                                <br>    

                                                              <div id="botones-para-compartir">
  <div class="col-sm-4">  
      <div class="fb-share-button" data-href="<?php echo $this->meta['url']; ?>" data-layout="button_count" data-size="small" data-mobile-iframe="true"><a class="fb-xfbml-parse-ignore" target="_blank" src="sdkpreparse">Compartir</a></div>
  </div>


  <div class="col-sm-4">
    <a href="https://twitter.com/share" class="twitter-share-button" data-via="bysatlantico" data-size="small">Tweet</a> <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
  </div>
  <div class="col-sm-4">

    <!-- Place this tag where you want the share button to render. -->
    <div class="g-plus" data-action="share"></div>
  </div>

  </div>
   </div>


  

                                <div class="clearfix"> </div>
                            </div>
                        </div>
                        
                        <div class="clearfix"> </div>
                    </div>
                    <!--Product Description-->
                        
                         
                    <!--Product Description-->
                </div>
            </div>
            <!--single-->
            <div class="new-arrivals-w3agile">
                    <div class="container">
                        <h3 class="tittle1">Relacionados</h3>
                        <div class="arrivals-grids">


                                <?php $ObjFotos = new Application_Model_DbTable_Fotos(); ?>

                                <?php foreach ($this->relacionados as $relacionado): ?>

                                <?php $fotos_rela=$ObjFotos->fetchRow('id_solicitud="'.$relacionado->id.'"'); ?>

                            <div class="col-md-3 arrival-grid simpleCart_shelfItem">
                                <div class="grid-arr" style="height: 30em;">
                                    <div  class="grid-arrival">
                                        <figure>        
                                            <a href="<?php echo $this->baseUrl('productos/ver/id/'.$relacionado->id); ?>">
                                                <div class="grid-img">
                                                    <img  src="<?php echo $this->baseUrl('assets/images/'.$fotos_rela['foto']); ?>" class="img-responsive" alt="<?php echo  $relacionado->nombre; ?>">
                                                </div>
                                                       
                                            </a>        
                                        </figure>   
                                    </div>
                                    
                                    
                                    <div class="women">
                                        <h6><a href="<?php echo $this->baseUrl('productos/ver/id/'.$relacionado->id); ?>"><?php echo  $relacionado->nombre; ?></a></h6>
                                        <span class="size"><?php echo  $relacionado->unidad; ?> </span>
                                        <p ><em class="item_price"><?php echo $relacionado->oferta ?></em></p>
                                        <a href="<?php echo $this->baseUrl('productos/ver/id/'.$relacionado->id); ?>" data-text="Add To Cart" class="my-cart-b item_add">Ver</a>
                                    </div>
                                </div>
                            </div>


                                <?php endforeach ?>



                            <div class="clearfix"></div>
                        </div>
                    </div>
                </div>
            <!--new-arrivals-->
        </div>
        <!--content-->
