
<?php 

header('Access-Control-Allow-Origin: *');
header("Access-Control-Allow-Headers: X-API-KEY, Origin, X-Requested-With, Content-Type, Accept, Access-Control-Request-Method");
header("Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE");
header("Allow: GET, POST, OPTIONS, PUT, DELETE");

$p = array();

foreach ($this->productos as $pro) {
	
	$pro['foto']="http://tiendacocomary.com/assets/images/".$pro['foto'];

	$p[]=$pro;

}

echo json_encode($p);
 ?>