
        <div class="banner1" style="background:url(<?php echo '/'.$this->nosotros['imagen']; ?>) no-repeat 0px 0px;     background-size: cover;">
            <div class="container">
                <h3><a href="<?php echo $this->baseUrl('/'); ?>">Inicio</a> / <a href="#"><?php echo $this->nosotros['titulo']; ?></a></h3>
            </div>
        </div>
    <!--banner-->







<div class="latest-w3">
                <div class="container">
                    
                    <div class="latest-grids">
                        <div class="col-sm-12 ">
                            <div class="latest-top">
                                <img  src="<?php echo $this->baseUrl($this->pasivos['imagen']); ?>" class="img-responsive"  alt="">                 
                            </div>
                        </div>
                        <div class="col-sm-12 ">
                            <div class="latest-top">
                                <h3 class="tittle1"> <?php echo $this->pasivos['titulo']; ?> </h3>
                                <div class="ingresos"> <?php echo $this->pasivos['contenido']; ?>  </div>
                            </div>
                        </div>
                       
                        <div class="clearfix"></div>
                    </div>
                    
                </div>
            </div>


<!--Products-->
            <div class="latest-w3">
                <div class="container">
                    <h3 class="tittle1">Servicios</h3>
                    <div class="latest-grids">

                        <?php foreach ($this->servicios as $serv): ?>
                            <div class="col-md-4 latest-grid">
                            <div class="latest-top">
                                <img  src="<?php echo $this->baseUrl($serv->imagen); ?>" class="img-responsive"  alt="<?php echo $serv->titulo; ?>">
                                <div class="latest-text">
                                    <h4><?php echo $serv->titulo; ?></h4>
                                </div>
                                
                            </div>
                        </div>
                        <?php endforeach ?>
                        
                        <div class="clearfix"></div>
                    </div>
                    
                </div>
            </div>
