<div class="container-fluid">
    
    <h1 class="page-header">
	
		Ventas
	
		<div class="pull-right col-xs-4 col-md-4 col-sm-6">
			<!--<a href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'add')); ?>"  class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart"></span> Agregar</a>-->

			<a href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'export','f_profession' => @$this->params['f_profession'], 'f_grado' => @$this->params['f_grado'], 'f_state' => @$this->params['f_state'], 'f_city' => @$this->params['f_city'])); ?>" target="_blank" class="btn btn-link"><span class="glyphicon glyphicon-export"></span> Exportar PDF</a>
		</div>
	
	
	</h1>

    <?php if (count($this->messages) > 0): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php foreach ($this->messages as $message): ?>
                <span><?php echo current($message); ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    
	<table class="table table-hover table-striped" id="tb_pedidos">
        <thead style="backgroun"><tr>
            <th>Id</th>
             <th >Telefono</th>
             <th >Cliente</th>
             <th >Direccion</th>
            <th>Total</th>
            <th class="hidden-xs">Fecha </th>
            <th>Observacion </th>
            <th >Estatus </th>
            
            <th class="text-center" >Acción</th>
            <th class="text-center" >Actualizar </th>
        </tr></thead><tbody>
        <?php foreach ($this->pedidos as $row): ?>
		
		      <?php $partes=explode(' ', $row->nombre) ?>

            <tr>
                <td><?php echo $row->id; ?></td>
                <td ><a target="_blanck" href="https://wa.me/57<?php echo $row->tlf; ?>?text= Hola <?php echo $partes[0]; ?>,Tienda Cocomary Te trae Nuevas promociones para el cuidado de tu piel y belleza, con grandes descuentos. Recuerda Todas nuestras promociones incluyen envio Gratis en toda Colombia. Te gustaria conocerlas."><?php echo $row->tlf; ?></a></td>
                <td ><?php echo $row->nombre; ?></td>
                <td ><?php echo $row->direccion; ?></td>
                <td><?php echo $row->total; ?></td>
                <td class="hidden-xs"><?php echo $row->fecha; ?></td>
                <td class="hidden-xs"><?php echo $row->descripcion_pedido; ?></td>

                <td class="etapa" data-idpedido="<?php echo $row->id; ?>" data-estatus="<?php echo $row->id_estatus_pedido ?>"> <span class="label label-<?php echo $row->clase;  ?>"> <?php echo $row->descripcion; ?></span> 
              

                </td>
               
                <td class="text-center" >
                    <div id="actiongroup" class="btn-group">
                        
                       
                        <a target="_blank" href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'detalle', 'id' => $row->id)); ?>" class="btn btn-default btn-sm" title="Editar"><span class="glyphicon glyphicon-print"></span> </a>


                        <a href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'edit', 'id' => $row->id)); ?>" class="btn btn-info btn-sm" title="Editar"><span class="glyphicon glyphicon-eye-open"></span> </a>



                        <button type="button" data-id="<?php echo $row->id; ?>" data-toggle="modal" data-target="" class="btn btn-danger btn-sm deletePedido" title="Eliminar"><span class="glyphicon glyphicon-trash"></span></button>
                        

                    </div>

                    
                </td>

                <td>    

                <div class="dropdown">
                      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        Estatus
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <li><a href="<?php echo $this->baseUrl('pedidos/updateestado/id/1/pedido/'.$row->id); ?>">Recibidos</a></li>

                        <li><a href="<?php echo $this->baseUrl('pedidos/updateestado/id/2/pedido/'.$row->id); ?>">Pagados</a></li>

                        <li><a href="<?php echo $this->baseUrl('pedidos/updateestado/id/3/pedido/'.$row->id); ?>">Cancelados</a></li>
                        
                        <li><a href="<?php echo $this->baseUrl('pedidos/updateestado/id/4/pedido/'.$row->id); ?>">Entregados</a></li>

                        <li><a href="<?php echo $this->baseUrl('pedidos/updateestado/id/5/pedido/'.$row->id); ?>">Enviados</a></li>
                      </ul>
                    </div>

                </td>
            </tr>
        <?php endforeach; ?>
		</tbody>
	</table>
    
    
</div>

<div id="approveModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Aprobar Miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Seguro desea realizar esta acción?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary approve">Aceptar</button>
                <form id="formApprove" name="formApprove" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'approve')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="rejectModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Rehazar Miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Seguro desea realizar esta acción?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger reject">Aceptar</button>
                <form id="formReject" name="formReject" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'reject')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="pendingModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Cambiar estatus de miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea cambiar el estatus del miembro a pendiente?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary pending">Aceptar</button>
                <form id="formPending" name="formPending" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'pending')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar Producto</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar el Producto?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger delete">Borrar</button>
                <form id="formDelete" name="formDelete" method="POST" action="<?php echo $this->url(array('controller' => 'productos', 'action' => 'delete')); ?>">
                    <input type="hidden" id="id" name="id" value="">
                </form>
            </div>
        </div>
    </div>
</div>

