<div class="container-fluid">
    <h1 class="page-header">Pedidos</h1>
    
    <div class="row">

        <div class="row">

            <h1 class="page-header">Detalle Del Pedido</h1>


    <form id="form_clientes" name="form_pedidos" enctype="multipart/form-data" action="<?php echo $this->baseUrl('pedidos/edit/id/'.$this->id) ?>" method="POST">
    
        <div class="well form-inline col-xs-12 col-md-12  form_agregar_detalle">
        
        <div class="form-group col-sm-4">
            <select id="id_cliente" name="id_cliente" class="form-control ">
                <option value="">--Clientes--</option>
                <?php foreach ($this->clientes as $c): ?>
                <option 
                    <?php if ($c->id==$this->pedido['id_cliente']): ?>
                         <?php echo 'Selected' ?>
                     <?php endif ?> 
                    value="<?php echo $c->id; ?>" ><?php echo utf8_encode($c->nombre); ?></option>
                <?php endforeach; ?>
            </select>
        </div>


            <div class="form-group col-sm-2">
                <input type="text" name="descripcion" id="descripcion" value="<?php echo $this->ddescripcion; ?>" class="form-control col-sm-2" placeholder="Observacion">
            </div>


        <div class="form-group col-sm-2">
            <button type="submit"  class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Actualizar</button>
            
        </div>
        
        </div>

    </form>
    
    </div>









<div class="row">

    <h1 class="page-header">Agregar Productos</h1>


    <form id="form_clientes" name="form_estudiantes" enctype="multipart/form-data" action="<?php echo $this->baseUrl('pedidos/adddetalle') ?>" method="POST">
	
		<div class="well form-inline col-xs-12 col-md-12  form_agregar_detalle">
        
        <div class="form-group col-sm-4">
            <select id="id_producto" name="id_producto" class="form-control ">
                <option value="">--Productos--</option>
                <?php foreach ($this->productos as $producto): ?>
                <option value="<?php echo $producto->id; ?>" ><?php echo utf8_encode($producto->nombre.' '.$producto->oferta); ?></option>
                <?php endforeach; ?>
            </select>
        </div>


            <div class="form-group col-sm-2">
                <input type="text" name="nota" id="nota" value="" class="form-control col-sm-2" placeholder="Nota">
            </div>

            <div class="form-group col-sm-2">
                <input type="text" name="cantidad" id="cantidad" value="1" class="form-control col-sm-2"  placeholder="Cantidad">
            </div>

            <input type="hidden" name="id_pedido" id="id_pedido" value="<?php echo $this->id; ?>" class="form-control col-sm-2">


        <div class="form-group col-sm-2">
            <button type="submit"  data-url="<?php echo $this->baseUrl('ajax/detalle'); ?>" class="btn btn-default"><span class="glyphicon glyphicon-plus"></span> Agregar</button>
            
        </div>
        
		</div>

    </form>
	
	</div>


            <!--++++++++++++++++++++ Comienzo del formulario ++++++++++++++++++-->
<div class="row">

<?php $total_general=0; ?>
<table class="table table-hover table-striped" id="tb_estudiantes2">
        <thead style=""><tr>
            <th>Id</th>
             <th>Descripcion</th>
            <th>Cantidad</th>
            <th class="hidden-xs">Precio </th>
            <th>Total </th>
            <th>Acción </th>
            
            
        </tr></thead><tbody id="tbody_detalle">
        <?php foreach ($this->detalles as $row): $total_general=$total_general+$row->total;?>
		

            <tr id="<?php echo $row->id; ?>">
                <td><?php echo $row->id; ?></td>
                <td ><?php echo $row->nombre; ?> </td>
                <td><?php echo $row->cantidad; ?></td>
                <td class="hidden-xs"><?php echo $row->precio; ?></td>

                <td> <span class="total"> <?php echo $row->total; ?></span> </td>
                <td> 
                    <a class="btn btn-danger" href="<?php echo $this->baseUrl('pedidos/deldetalle/id/'.$row->id); ?>">Eliminar</a>

                </td>
                
            </tr>
        <?php endforeach; ?>
		</tbody>
        <tfoot>
            <tr>
                <td id="ultima_fila" colspan="7">Total de Pedido:<span class="total_general"> <?php echo $total_general; ?> </span> </td>
            </tr>
        </tfoot>
	</table>

</div>


 <div class="row">
     <a name="btn_cancel" href="<?php echo $this->baseUrl('/pedidos') ?>" id="btn_cancel" type="button" class="btn btn-danger">Volver</a>
 </div>      





    </div>
    
</div>




