<div class="container-fluid">
    
    <h1 class="page-header">
	
		Ventas por dia
	
		<div class="pull-right col-xs-4 col-md-4 col-sm-6">
			<!--<a href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'add')); ?>"  class="btn btn-primary"><span class="glyphicon glyphicon-shopping-cart"></span> Agregar</a>-->

			<a href="<?php echo $this->url(array('controller' => 'pedidos', 'action' => 'export','f_profession' => @$this->params['f_profession'], 'f_grado' => @$this->params['f_grado'], 'f_state' => @$this->params['f_state'], 'f_city' => @$this->params['f_city'])); ?>" target="_blank" class="btn btn-link"><span class="glyphicon glyphicon-export"></span> Exportar PDF</a>
		</div>
	
	
	</h1>

    <?php if (count($this->messages) > 0): ?>
        <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <?php foreach ($this->messages as $message): ?>
                <span><?php echo current($message); ?></span><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
    
	
		
	
   
	
		<table class="table table-hover table-striped" id="tb_pedidos">
        <thead style="backgroun"><tr>
            <th>Id</th>
             <th >Fecha</th>
             <th >Cantidad</th>
             <th >Costo</th>
            <th>Total</th>
            <th>Ganancia  </th>
        </tr></thead><tbody>
        <?php foreach ($this->pedidos as $row): ?>
		
            <tr>
                <td><?php echo $row->id; ?></td>
                <td ><?php echo $row->fecha; ?></td>
                <td ><?php echo $row->cantidad_ventas; ?></td>
                <td ><?php echo $row->total_costo; ?></td>
                <td><?php echo $row->total_ventas; ?></td>
                <td><?php echo $row->total_ventas-$row->total_costo-($row->cantidad_ventas*6000); ?></

            </tr>
        <?php endforeach; ?>
		</tbody>
	</table>
    
    
</div>

<div id="approveModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Aprobar Miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Seguro desea realizar esta acción?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary approve">Aceptar</button>
                <form id="formApprove" name="formApprove" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'approve')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="rejectModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Rehazar Miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Seguro desea realizar esta acción?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger reject">Aceptar</button>
                <form id="formReject" name="formReject" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'reject')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="pendingModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Cambiar estatus de miembro</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea cambiar el estatus del miembro a pendiente?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary pending">Aceptar</button>
                <form id="formPending" name="formPending" method="POST" action="<?php echo $this->url(array('controller' => 'members', 'action' => 'pending')); ?>">
                    <input type="hidden" id="mid" name="mid" value="">
                </form>
            </div>
        </div>
    </div>
</div>

<div id="deleteModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Eliminar Producto</h4>
            </div>
            <div class="modal-body">
                <p>¿Está seguro que desea eliminar el Producto?</p>
                <p class="debug-url"></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-danger delete">Borrar</button>
                <form id="formDelete" name="formDelete" method="POST" action="<?php echo $this->url(array('controller' => 'productos', 'action' => 'delete')); ?>">
                    <input type="hidden" id="id" name="id" value="">
                </form>
            </div>
        </div>
    </div>
</div>

